### ISSUE TITLE
Tiddloid / Tiddloid Lite save error on Android 11

### ISSUE THREAD

**Issue by hubertgk** [donmor/Tiddloid#25] opened 2021-12-11 17:16 UTC
Originally reported in [this Google Groups thread](https://groups.google.com/g/tiddlywiki/c/XRynWS0J4R0), I've experienced this issue today after installing Tiddloid on my Android 11 phone (no issues found on Android 8), saving my wiki and reloading.

Issue:

Code that appears to belong to the boot.js core tiddler is shown "underneath" the password encryption prompt and normal tiddlers after launching wiki can be seen on screenshots below.

![tiddloid_code_issue1](https://user-images.githubusercontent.com/25121125/145685486-297ff7d3-7039-41ad-8224-bbb6fb467313.png)

![tiddloid_code_issue2](https://user-images.githubusercontent.com/25121125/145685487-ea577b8e-4b88-4566-992c-ffaccd152f12.png)

In my Android 8 phone this was never an issue and I've been using Tiddloid Lite for years. The issue now appeared on my Android 11 phone, Tiddloid versions are the same on both phones.

Steps to reproduce:

1. Open an (encrypted) TiddlyWiki in Tiddloid or Tiddloid Lite (on Android 11)
2. Save the wiki
3. Reopen the wiki

The code appears "underneath" the tiddler frame after the wiki is saved by Tiddloid/Tiddloid Lite and then reopened. Once it's saved like this, the code will also show on any mobile or desktop browser, it appears "burned in" but how much of the code is revealed depends on the height of the tiddler. It may take a few saves before it happens but once it does it is impossible to get rid of the code.

**Comment by donmor** [comment] 2021-12-11 17:31
The code is, infact, remain of last veraion of your file. If opened in a text editor, you can find at least two `</html>`in the corrupted file.
This seems to be a bug of Android 11, which caused files cannot be shrinked if accessed via SAF. Many issues created here due to this annoying problem. Currently no workaround found, but you can fix your file by deleting all content behind the first `</html>`.

**Comment by hubertgk** [comment] 2021-12-11 17:49
Thanks for a quick reply donmor. I was suspecting this was related to the Android version.

I know you said no workaround currently and that saving corrupts files but at least the corruption can be manually reversed.

Do you think there is scope for a fix with Android's current SAF implementation in the longer term?

Thanks.

**Comment by hubertgk** [comment] 2021-12-24 16:47
Hi @donmor 

Maybe you could consider implementing the fallback saver as a temporary fix on Android 11+? This would basically download a copy of the html file in the same way as browsers normally do by default with single file wikis.

Another solution would be for Tiddloid to create its own folder in the Android/data folder and save to that folder because Android should allow access to that folder only.

Please let me know if any of these solutions are feasible?

Many thanks

**Comment by donmor** [comment] 2021-12-24 17:14
> Maybe you could consider implementing the fallback saver as a temporary fix on Android 11+? This would basically download a copy of the html file in the same way as browsers normally do by default with single file wikis.

But how to save the file? If using SAF chooser then you have to create a new file each time, and Google is blocking the legacy file:// protocol on interal storage.

>Another solution would be for Tiddloid to create its own folder in the Android/data folder and save to that folder because Android should allow access to that folder only.

A nice idea for local-only notes, but these files can't be synced across devices, because Android/data is not accessable to 3rd party apps.

The best workaround is to use legacy mode: Find a file manager designed for Android <4.4, and open the HTML file with "Add to Tiddloid". You need some 3rd party apps to sync the file.

**Comment by donmor** [comment] 2022-02-05 07:36
Are you using cloud services that support WebDAV? Now you can checkout the latest 2.2.0-pre version [here](https://github.com/donmor/Tiddloid/releases/tag/2.2.0-pre) (This is a pre-release with a debug package)

**Comment by hubertgk** [comment] 2022-02-07 12:17
Hi Donmor, thanks. I'm not using WebDav (I prefer to work off an offline
copy of the tw file) but I'd like to try the legacy mode that you mentioned
in the Discourse group.

Unfortunately, I'm unable to install the debug apk file. I don't have any
Tiddloid apps installed at the moment but when I try to install the apk
file Android says that the apk package is invalid.

Thanks,
Hubert

**Comment by wallacerunner** [comment] 2022-05-13 01:33
I seem to have similar issue, Android 11, now updated to 12, TW is encrypted, saving via Tiddloid adds this line on top of password form and under the tiddlers area:
`/ Check that no other outstanding tasks must be executed before this one for(t=0; t`
The rest, I think, is gracefully hidden by browser.

I checked further, and it is in fact the same issue, I found two `</html>` tags in there.

Then I have only one question: the added code doesn't seem to do anything, is it safe to leave this corruption as is, or should I take action on it?

**Comment by donmor** [comment] 2022-05-13 01:36
Currently it is not reported insecure. The next version will have a temporary workaround, see #23 .

**Comment by donmor** [comment] 2022-09-10 14:12
Hmm... Should I close this as this issue is duplicated to #23?

**Comment by Dialga** [comment] 2022-09-10 18:40
This is a duplicate of #23, check https://stackoverflow.com/questions/56902845/how-to-properly-overwrite-content-of-file-using-android-storage-access-framework on solutions on how to fix.

**Comment by donmor** [comment] 2022-09-24 14:52
Okay I uploaded 2.3.0 to [GitHub](https://github.com/donmor/Tiddloid/releases/tag/2.3.0)/[Gitee](https://gitee.com/donmor/Tiddloid/releases/tag/2.3.0)/[CoolApk](https://www.coolapk.com/apk/top.donmor.tiddloid) ([F-droid](https://f-droid.org/packages/top.donmor.tiddloid/) version needs some time to be built). Try it and let me know if it ceased your problem.

**Comment by donmor** [comment] 2023-03-05 07:32
Does anyone still have problem with 2.3.0 or later? I may close this if no problem reported.

**Comment by donmor** [comment] 2023-03-10 14:19
No more bug reports since 2.3.0. Closing this. Reopen it if you're still concerned.

**Closed by donmor** 2023-03-10 14:19 UTC
Labels: duplicate
